name: Publish preview update

on:
  push:
    branches: ['develop']

jobs:
  publish_preview_update:
    name: Publish preview update
    type: update
    params:
      branch: ${{ github.ref || 'test' }}
