name: PR Request

on:
  pull_request_labeled:
    labels:
      - 'Preview'

jobs:
  build:
    type: build
    params:
      platform: ios
      profile: development
  e2e:
    type: maestro
    needs: [build]
    environment: development 
    params:
      build_id: ${{ needs.build.outputs.build_id }}
      flow_path: | 
        .maestro/choose_destination.yml
