name: PR Request

on:
  pull_request:
    branches:
      - 'main'
      - 'develop'
    types:
      - opened

jobs:
  e2e:
    name: E2E tests
    type: maestro
    environment: preview 
    params:
      build_id: a700613f-b3ee-408b-a5cd-820f29a33c21 # TODO: Dynamically set this value
      flow_path: | 
        maestro/choose_destination.yml
