name: PR Request E2E

on:
  pull_request_labeled:
    labels:
      - 'E2E'

jobs:
  update:
    type: update
    params:
      message: E2E test triggered by PR
      platform: ios
      channel: preview  

  e2e:
    steps:
      - name: Run Moropo E2E
        run: >-
          curl -X 'POST' \
          'https://api.moropo.com/testRuns' \
          -H 'accept: */*' \
          -H 'x-app-api-key: a4f4ea58-940f-4abe-8f75-f5cbf4dab155' \
          -H 'Content-Type: application/json' \
          -d '{"ciCdId": "7f85fcc7-33a7-416b-b342-cdf16a869dcf"}'
