name: PR Request E2E

on:
  pull_request_labeled:
    labels:
      - 'E2E'

jobs:
  # build:
  #   type: build
  #   params:
  #     platform: ios
  #     profile: preview
  # # e2e:
  #   type: maestro
  #   needs: [build]
  #   environment: preview 
  #   params:
  #     build_id: ${{ needs.build.outputs.build_id }}
  #     flow_path: | 
  #       maestro/choose_destination.yml

  e2e:
    steps:
      - name: Run Moropo E2E
        run: >-
          curl -X 'POST' \
          'https://api.moropo.com/testRuns' \
          -H 'accept: */*' \
          -H 'x-app-api-key: $MOROPO_API_KEY' \
          -H 'Content-Type: application/json' \
          -d '{"ciCdId": "7f85fcc7-33a7-416b-b342-cdf16a869dcf"}'
