name: PR Request E2E

on:
  pull_request_labeled:
    labels:
      - 'E2E'

jobs:
  build:
    type: build
    params:
      platform: ios
      profile: preview
  e2e:
    type: maestro
    needs: [build]
    environment: preview 
    params:
      build_id: ${{ needs.build.outputs.build_id }}
      flow_path: | 
        maestro/choose_destination.yml
