name: Pre Release Check
on:
  pull_request:
    branches:
      - 'main'
    types:
      - opened

jobs:
  build:
    type: build
    params:
      platform: ios
      profile: development
  e2e:
    type: maestro
    needs: [build]
    environment: development 
    params:
      build_id: ${{ needs.build.outputs.build_id }}
      flow_path: | 
        .maestro/choose_destination.yml
